on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go1.16 release
        uses: shoukoo/golang-pipeline/go1.16/release@master
        env:
          PROJECT_PATH: "."