name: pr

on: push

jobs:
  full_ci:
    strategy:
      matrix:
        go-version: [ 1.14.x ]

    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        run: go test -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annoations@v0.3.0
        with:
          test-results: test.json